version: '3.5'

services:

  database:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  musicalroom-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPLICATION_ARTIFACT_NAME: ${APP_NAME}
        APPLICATION_VERSION: ${APP_VERSION}
        DATABASE_HOST: ${DB_HOST}
        DATABASE_PORT: ${DB_PORT}
    depends_on:
      - database
    restart: always
    ports:
      - "${APP_PORT}:8080"
