version: '3.5'

services:

  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"

  adminer:
    image: adminer:4-standalone
    restart: always
    depends_on:
      - postgres
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: postgres
    ports:
    - "${ADMINER_PORT}:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPLICATION_ARTIFACT_NAME: ${APP_NAME}
        APPLICATION_VERSION: ${APP_VERSION}
        DATABASE_HOST: ${PG_HOST}
        DATABASE_PORT: ${PG_PORT}
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
