version: '3.5'

services:

  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"

  core:
    build:
      context: .
      dockerfile: Dockerfile-core
      args:
        APPLICATION_ARTIFACT_NAME: ${APP_NAME}
        DATABASE_HOST: ${PG_HOST}
        DATABASE_PORT: ${PG_PORT}
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"

  external:
    build:
      context: .
      dockerfile: Dockerfile-external
    restart: always
    ports:
      - "8090:8090"
